/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots['source-renderer ok'] = `<div id="details">
  <img
    alt="me"
    src="/assets/me.jpg"
  >
  <h1>
    Rodrigo García León
  </h1>
  <p>
    Full Stack Developer 🙌✨
  </p>
  <hr>
  <ul>
    <li>
      <a
        href="https://twitter.com/twin_tigon"
        rel="noopener noreferrer nofollow"
        target="_blank"
      >
        Twitter
      </a>
    </li>
    <li>
      <a
        href="https://www.instagram.com/twin_tigon"
        rel="noopener noreferrer nofollow"
        target="_blank"
      >
        Instagram
      </a>
    </li>
    <li>
      <a
        href="https://www.linkedin.com/in/rgarcialeon/"
        rel="noopener noreferrer nofollow"
        target="_blank"
      >
        LinkedIn
      </a>
    </li>
  </ul>
  <p>
    <a href="mailto:yo@rodrigogarcia.me">
      yo@rodrigogarcia.me
    </a>
  </p>
</div>
<div id="projects">
  <div id="keywords">
    <ul>
      <li>
        <a
          class="selected"
          href="#"
        >
          front-end
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          lit
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-components
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          open-wc
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          modern-web
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          esbuild
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          skypack
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          javascript
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          plugin
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          typescript
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          python
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          fastapi
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          vue
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          slidev
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          houdini
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-sockets
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          back-end
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          django
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          postgresql
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          redis
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          docker
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          psychoacoustics
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          digital-signal-processing
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          matlab
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          jwt
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          go
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-audio
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-assembly
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          rust
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          progressive-web-app
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          react
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          koa
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          graphql
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          nodejs
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          devops
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          google-cloud-platform
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          kubernetes
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          shell
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          cli
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          gamedev
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          game-jam
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          platform-game
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          puzzle-game
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          godot
        </a>
      </li>
    </ul>
  </div>
  <div id="cards">
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/website"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          website
        </a>
      </h2>
      <p>
        This website 👀
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/esbuild-skypack-resolver"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          esbuild-skypack-resolver
        </a>
      </h2>
      <p>
        An esbuild plugin to resolve package names to Skypack CDN URLs
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/hypermodern-python-talk"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          hypermodern-python-talk
        </a>
      </h2>
      <p>
        Resources for the Hypermodern Web Development using Python and FastAPI talk
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/web-hacks"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          web-hacks
        </a>
      </h2>
      <p>
        Web Hacks 🕸🤓
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/chat-groups-app"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          chat-groups-app
        </a>
      </h2>
      <p>
        Slack clone app built with Vue
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/chat-groups-api"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          chat-groups-api
        </a>
      </h2>
      <p>
        Slack clone API built with Django
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/thesis-matlab"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          thesis-matlab
        </a>
      </h2>
      <p>
        Collection of MATLAB scripts and toolboxes regarding my Master Thesis on psychoacoustics
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/authentication-api"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          authentication-api
        </a>
      </h2>
      <p>
        Authentication API using JWT built with Go and Redis
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/glissando-daw/glissando-daw"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          glissando-daw
        </a>
      </h2>
      <p>
        A web-based digital audio workstation using the web platform APIs (Web Audio, Web MIDI) and WebAssembly
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/hn-app"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          hn-app
        </a>
      </h2>
      <p>
        Hacker News PWA built with React Hooks
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/hn-api"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          hn-api
        </a>
      </h2>
      <p>
        Hacker News API using GraphQL
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/cloud"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          cloud
        </a>
      </h2>
      <p>
        Collection of scripts to manage Google Cloud Platform and Kubernetes ☁️
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/tictactoe-cli"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          tictactoe-cli
        </a>
      </h2>
      <p>
        Tic-tac-toe implementation in Rust
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/senescence"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          senescence
        </a>
      </h2>
      <p>
        Senescence is a narrative puzzle platformer made for GMTK Game Jam 2020
      </p>
    </div>
  </div>
</div>
`;
/* end snapshot source-renderer ok */

snapshots['source-renderer _selectedKeyword'] = `<div id="details">
  <img
    alt="me"
    src="/assets/me.jpg"
  >
  <h1>
    Rodrigo García León
  </h1>
  <p>
    Full Stack Developer 🙌✨
  </p>
  <hr>
  <ul>
    <li>
      <a
        href="https://twitter.com/twin_tigon"
        rel="noopener noreferrer nofollow"
        target="_blank"
      >
        Twitter
      </a>
    </li>
    <li>
      <a
        href="https://www.instagram.com/twin_tigon"
        rel="noopener noreferrer nofollow"
        target="_blank"
      >
        Instagram
      </a>
    </li>
    <li>
      <a
        href="https://www.linkedin.com/in/rgarcialeon/"
        rel="noopener noreferrer nofollow"
        target="_blank"
      >
        LinkedIn
      </a>
    </li>
  </ul>
  <p>
    <a href="mailto:yo@rodrigogarcia.me">
      yo@rodrigogarcia.me
    </a>
  </p>
</div>
<div id="projects">
  <div id="keywords">
    <ul>
      <li>
        <a
          class="selected"
          href="#"
        >
          front-end
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          lit
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-components
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          open-wc
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          modern-web
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          esbuild
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          skypack
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          javascript
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          plugin
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          typescript
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          python
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          fastapi
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          vue
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          slidev
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          houdini
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-sockets
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          back-end
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          django
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          postgresql
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          redis
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          docker
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          psychoacoustics
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          digital-signal-processing
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          matlab
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          jwt
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          go
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-audio
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          web-assembly
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          rust
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          progressive-web-app
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          react
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          koa
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          graphql
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          nodejs
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          devops
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          google-cloud-platform
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          kubernetes
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          shell
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          cli
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          gamedev
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          game-jam
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          platform-game
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          puzzle-game
        </a>
      </li>
      <li>
        <a
          class="selected"
          href="#"
        >
          godot
        </a>
      </li>
    </ul>
  </div>
  <div id="cards">
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/website"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          website
        </a>
      </h2>
      <p>
        This website 👀
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/esbuild-skypack-resolver"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          esbuild-skypack-resolver
        </a>
      </h2>
      <p>
        An esbuild plugin to resolve package names to Skypack CDN URLs
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/hypermodern-python-talk"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          hypermodern-python-talk
        </a>
      </h2>
      <p>
        Resources for the Hypermodern Web Development using Python and FastAPI talk
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/web-hacks"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          web-hacks
        </a>
      </h2>
      <p>
        Web Hacks 🕸🤓
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/chat-groups-app"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          chat-groups-app
        </a>
      </h2>
      <p>
        Slack clone app built with Vue
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/chat-groups-api"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          chat-groups-api
        </a>
      </h2>
      <p>
        Slack clone API built with Django
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/thesis-matlab"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          thesis-matlab
        </a>
      </h2>
      <p>
        Collection of MATLAB scripts and toolboxes regarding my Master Thesis on psychoacoustics
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/authentication-api"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          authentication-api
        </a>
      </h2>
      <p>
        Authentication API using JWT built with Go and Redis
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/glissando-daw/glissando-daw"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          glissando-daw
        </a>
      </h2>
      <p>
        A web-based digital audio workstation using the web platform APIs (Web Audio, Web MIDI) and WebAssembly
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/hn-app"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          hn-app
        </a>
      </h2>
      <p>
        Hacker News PWA built with React Hooks
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/hn-api"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          hn-api
        </a>
      </h2>
      <p>
        Hacker News API using GraphQL
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/cloud"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          cloud
        </a>
      </h2>
      <p>
        Collection of scripts to manage Google Cloud Platform and Kubernetes ☁️
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/tictactoe-cli"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          tictactoe-cli
        </a>
      </h2>
      <p>
        Tic-tac-toe implementation in Rust
      </p>
    </div>
    <div class="project">
      <h2>
        <a
          href="https://github.com/twin-tigon/senescence"
          rel="noopener noreferrer nofollow"
          target="_blank"
        >
          senescence
        </a>
      </h2>
      <p>
        Senescence is a narrative puzzle platformer made for GMTK Game Jam 2020
      </p>
    </div>
  </div>
</div>
`;
/* end snapshot source-renderer _selectedKeyword */
