name: Main
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Screenshots
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: update-visual-baseline.yml
          workflow_conclusion: success
          event: push
          name: screenshots
          path: ./test/__screenshots__
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBSITE_A9706 }}'
          projectId: website-a9706
          channelId: live
