name: Update Visual Baseline
on:
  push:
    branches:
      - update-visual-baseline

jobs:
  update-visual-baseline:
    name: Update Visual Baseline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Update Visual Baseline
        run: npm run test:visual-regression:update
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ./test/__screenshots__